name: rtd
channels:
  - conda-forge
  - defaults
dependencies:
  - slycot
  - pip
  - pip:
    - numpy
    - scipy
    - control
    - cvxpy
    - joblib
    - pytest
    - pytest-regressions
    - sphinx
    - sphinx-rtd-theme
    - ruff
