name: rtd
channels:
  - conda-forge
  - defaults
dependencies:
  - slycot
  - pip
  - numpy
  - scipy
  - control
  - cvxpy
  - joblib
  - matplotlib
  - pytest
  - pytest-regressions
  - sphinx
  - sphinx-rtd-theme
  - ruff
